service: bsi-bim

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  profile: bsi


  iamRoleStatements:
    - Effect: "Allow"
      Action: "*"
      Resource: "*"

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  hello:
    handler: handler.hello

# you can add CloudFormation resource templates here
resources:
 Resources:
  qldbLedger:
    Type: AWS::QLDB::Ledger
    Properties:
      Name: qldb-ledger-${self:provider.stage}
      DeletionProtection: false
      PermissionsMode: ALLOW_ALL

  # QLldbServiceRole:
  #   Type: "AWS::IAM::Role"
  #   Properties:
  #     RoleName: "Qldb-Service-${self:provider.stage}"
  #     AssumeRolePolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         - Effect: "Allow"
  #           Principal:
  #             Service:
  #               - "appsync.amazonaws.com"
  #           Action:
  #             - "qldb:*"
  #     Policies:
  #       - PolicyName: "Qldb-Policy"
  #         PolicyDocument:
  #           Version: "2012-10-17"
  #           Statement:
  #             - Effect: "Allow"
  #               Action: "*"
  #               Resource: "*"

#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
